---
title: "Bins of Significance"
keep_md: no
author: "Ryan Ward"
date: '2022-05-04'
output: html_document
---
```{r overlap calculations}
library(pacman)

p_load(eulerr, data.table, viridis, grid, ComplexHeatmap, tidyverse, ComplexUpset, ggsankey)

interest <- fread("../../interest.tsv", sep = "\t")

median_melted_results <- fread("../../Results/median_melted_results.tsv.gz")

bins <- 
	median_melted_results[
		, .(significant = FDR < 0.05 & medLFC < -1), 
		by = .(condition, unique_name, type)]

bins <- bins[condition %in% c("None_0_T1 - None_0_T0", "None_0_T2 - None_0_T0")]

bins <-
	dcast(bins, unique_name + type ~ condition, value.var = "significant")

# bins[`None_0_T1 - None_0_T0` == FALSE & `None_0_T2 - None_0_T0` == FALSE, `Never Vulnerable` := TRUE]
bins[`None_0_T1 - None_0_T0` == FALSE & `None_0_T2 - None_0_T0` == FALSE, `All Genes` := TRUE]

bins[is.na(`All Genes`), `All Genes` := TRUE]
```
```{r venn diagram, fig.width=8, fig.height=8}

p.euler <- bins[type == "perfect"] %>% dplyr::select (-c(unique_name, type)) %>% euler

p <- plot(
	p.euler,
	fill = viridis(3, option = "magma", direction = -1, alpha = 0.45), 
	quantities = T,
	lwd = 5)

oldGrob <- getGrob(p, "tag.label.1")
newGrob <- editGrob(oldGrob, label = bquote(bold(18)~Hours))
p <- setGrob(p, "tag.label.1", newGrob)

oldGrob <- getGrob(p, "tag.label.2")
newGrob <- editGrob(oldGrob, label = bquote(bold(36)~Hours))
p <- setGrob(p, "tag.label.2", newGrob)

oldGrob <- getGrob(p, "tag.label.3")
newGrob <- editGrob(oldGrob, label = bquote(bold(The~Rest)))
p <- setGrob(p, "tag.label.3", newGrob)

print(p)
```

```{r, fig.width=6, fig.height=4}
# 580 x 400
vulnerability.comb_mat <- 
    median_melted_results %>% 
    filter(type == "perfect") %>%
    mutate(depleted = (FDR < 0.05 & medLFC < -1)) %>%  
    pivot_wider(
        id_cols = unique_name, 
        names_from = condition, values_from = depleted) %>% 
    dplyr::select(`None_0_T1 - None_0_T0`, `None_0_T2 - None_0_T0`) %>% 
    make_comb_mat() 

UpSet(
    vulnerability.comb_mat, 
    top_annotation = HeatmapAnnotation(
        "Intersection" = anno_barplot(
            comb_size(vulnerability.comb_mat),
            border = FALSE, 
            height = unit(6, "cm"),
            add_numbers = T,
            gp = gpar(fill = "grey", lty = "blank")), 
        annotation_name_side = "right", 
        annotation_name_rot = 90,
        show_annotation_name = FALSE),
    right_annotation = rowAnnotation(
        "Genes Vulnerable Upon Induction" = anno_barplot(
            set_size(vulnerability.comb_mat),
            border = FALSE,
            gp = gpar(fill =  viridis(3, direction = -1, alpha = 0.5)[2:3], lwd = 3),
            width = unit(7, "cm"),
            add_numbers = T),
            annotation_name_gp = gpar(fontsize = 8)),
    set_order = order(set_size(vulnerability.comb_mat)),
    row_names_gp = grid::gpar(fontsize = 10),
    row_labels = c(
        as.expression(bquote(Vulnerable~at~t[1])), 
        as.expression(bquote(Vulnerable~at~t[2]))))
```

```{r sankey plot}
median_melted_results <- fread("../../Results/median_melted_results.tsv.gz")

sankey.levels <- c(
	"Highly Resistant",
	"Resistant",
	"No Response",
	"Vulnerable",
	"Highly Vulnerable")

five_pct_vuln <- median_melted_results %>% 
	filter(condition == "None_0_T2 - None_0_T0" & FDR < 0.05 & medLFC < -1) %>% 
	pull(medLFC) %>% 
	quantile(0.05)

sankey.df <- median_melted_results %>%
	filter(condition %in% c("None_0_T1 - None_0_T0", "None_0_T2 - None_0_T0")) %>%
	filter(type == "perfect") %>%
		mutate(
		Response = case_when(
			medLFC < five_pct_vuln  & FDR < 0.05 ~ "Highly Vulnerable",
			medLFC < -1 & FDR < 0.05 ~ "Vulnerable",
			medLFC > 1 & FDR < 0.05 ~ "Resistant",
			TRUE ~ "No Response")) %>%
	select(AB19606, condition, Response) %>%
	mutate(condition = case_when(
		condition == "None_0_T1 - None_0_T0" ~ "T1",
		condition == "None_0_T2 - None_0_T0" ~ "T2"))	%>%
	pivot_longer(!c(condition, AB19606)) %>%
	pivot_wider(id_cols = c(AB19606), names_from = condition, values_from = value) %>%
	make_long(`T1`, `T2`) %>%
	  mutate(
    node = factor(node, levels = sankey.levels),
    next_node = factor(next_node, levels = sankey.levels))

sankey.tally <- sankey.df %>% group_by(node, x) %>% tally

sankey.df %>% 
	inner_join(sankey.tally) %>%
	ggplot(aes(
		x = x,
		next_x = next_x,
		node = node,
		next_node = next_node,
		fill = factor(node),
		label = paste(node, n, sep = "\n"))) +
	geom_sankey(
		smooth = 6, 
		flow.colour = "black",
		flow.alpha = 0.25,
		node.color = "black") +
	scale_fill_manual(values = c(
		 "#e53935", "grey", "#ffb300")) +
	geom_sankey_label(aes(colour = "node"),
										size = 3.5, color = 1) +
	guides(
		fill = guide_legend(title = "Relative Response to Knockdown")) +
	theme(
		legend.position = "none",
		panel.background = element_blank(),
		panel.border = element_rect(colour = NA, fill=NA, size=1),
        axis.line = element_blank(),
        panel.grid = element_blank(),
        axis.text.x   = element_text(size = 12, color = "black",family = "Arial",hjust = 0.5, angle = 0),
        axis.text.y   = element_blank(),
        axis.title  = element_blank(),
        axis.ticks =  element_blank())
```

```{r sankey plot 2}
median_melted_results <- fread("../../Results/median_melted_results.tsv.gz")

sankey.levels <- c(
	"Highly Resistant",
	"Resistant",
	"No Response",
	"Vulnerable",
	"Highly Vulnerable")

five_pct_vuln <- median_melted_results %>% 
	filter(condition == "None_0_T2 - None_0_T0" & FDR < 0.05 & medLFC < -1) %>% 
	pull(medLFC) %>% 
	quantile(0.05)

sankey.df <- median_melted_results %>% filter(base == "None_0_T0") %>%
	filter(type == "perfect") %>%
		mutate(
		Response = case_when(
			medLFC < five_pct_vuln  & FDR < 0.05 ~ "Highly Vulnerable",
			medLFC < -1 & FDR < 0.05 ~ "Vulnerable",
			medLFC > 1 & FDR < 0.05 ~ "Resistant",
			TRUE ~ "No Response")) %>%
	select(AB19606, condition, Response) %>%
	mutate(condition = case_when(
		condition == "None_0_T1 - None_0_T0" ~ "T1",
		condition == "None_0_T2 - None_0_T0" ~ "T2"))	%>%
	pivot_longer(!c(condition, AB19606)) %>%
	filter(!is.na(condition)) %>%
	pivot_wider(id_cols = c(AB19606), names_from = condition, values_from = value) %>%
	make_long(`T1`, `T2`) %>%
	  mutate(
    node = factor(node, levels = sankey.levels),
    next_node = factor(next_node, levels = sankey.levels))

sankey.tally <- sankey.df %>% group_by(node, x) %>% tally

sankey.df %>% 
	inner_join(sankey.tally) %>%
	ggplot(aes(
		x = x,
		next_x = next_x,
		node = node,
		next_node = next_node,
		fill = factor(node),
		label = paste(node, n, sep = "\n"))) +
	geom_sankey(
		smooth = 6, 
		flow.colour = "black",
		flow.alpha = 0.25,
		node.color = "black") +
	scale_fill_manual(
		values = c(
			 "#E31A1C", "grey", "#FB9A99")) +
	geom_sankey_label(
		aes(colour = "node"),
		size = 3.5, 
		colour = c("black", "black", "black", "black", "black")) +
		geom_sankey_text(
		aes(colour = "node"),
		size = 3.5, 
		colour = c("black", "black", "black", "black", "white")) +
	guides(
		fill = guide_legend(title = "Relative Response to Knockdown")) +
	theme(
		legend.position = "none",
		panel.background = element_blank(),
		panel.border = element_rect(
			colour = NA, 
			fill = NA, 
			size = 1),
        axis.line = element_blank(),
        panel.grid = element_blank(),
        axis.text.x   = element_text(
        	size = 14, 
        	color = "black", 
        	family = "Arial",
        	hjust = 0.5, 
        	angle = 0),
        axis.text.y   = element_blank(),
        axis.title  = element_blank(),
        axis.ticks =  element_blank())
```

```{r}
sankey.combined.df <- 
	median_melted_results %>% 
	arrange(medLFC)	%>% 
	filter(base == "None_0_T0") %>% 
	filter(type == "perfect") %>% 
	separate(shift, c("Drug", "Dose", "Timing"), sep = "_") %>% 
	mutate(
		Response = case_when(
		abs(medLFC) > 1 & FDR < 0.05 ~ "Responsive",
		TRUE ~ "No Response")) %>% 
	group_by(AB19606, Timing, Response) %>% 
	tally %>% 
	pivot_wider(id_cols = c(AB19606, Timing), names_from = Response, values_from = n, values_fill = 0) %>% 
	mutate(Response = case_when(`No Response` == 7 ~ "No Response", TRUE ~ "Responsive")) %>% 
	ungroup %>% 
	pivot_wider(id_cols = c(AB19606), names_from = Timing, values_from = Response) %>% 
	make_long(`T1`, `T2`) %>% 	 
	mutate(
		node = factor(node, levels = c("No Response", "Responsive")),
		next_node = factor(next_node, levels = c("No Response", "Responsive")))

sankey.combined.tally <- 
	sankey.combined.df %>% 
	group_by(node, x) %>% 
	tally

sankey.combined.df %>% 
	inner_join(sankey.combined.tally) %>%
	ggplot(aes(
		x = x,
		next_x = next_x,
		node = node,
		next_node = next_node,
		fill = factor(node),
		label = paste(node, n, sep = "\n"))) +
	geom_sankey(
		smooth = 6, 
		flow.colour = "black",
		flow.alpha = 0.25,
		node.color = "black") +
	scale_fill_manual(values = c(
		"grey", "#80e27e")) +
	geom_sankey_label(
		aes(colour = "node"),
		size = 3.5, color = 1) +
	guides(
		fill = guide_legend(title = "Relative Response to Knockdown")) +
	theme(
		legend.position = "none",
		panel.background = element_blank(),
		panel.border = element_rect(colour = NA, fill = NA, size = 1),
		axis.line = element_blank(),
		panel.grid = element_blank(),
		axis.text.x = element_text(size = 14, color = "black",family = "Arial",hjust = 0.5, angle = 0),
		axis.text.y = element_blank(),
		axis.title = element_blank(),
		axis.ticks = element_blank())

```
