---
title: "Colistin Rifampicin Signature Comparison at T2"
keep_md: no
author: "Ryan Ward"
date: '2022-05-08'
output: html_document
---

```{r load packages}
library(pacman)

p_load(data.table, viridis, grid, ComplexHeatmap, tidyverse)
```

Read results previously calculated using edgeR.

```{r read results}
median_melted_results <- fread("../../Results/median_melted_results.tsv.gz")
```
Generate list of conditions we are interested in looking at. Some are stored already as "interest", but we are adding even more, which inclde the T0 contrasts.

```{r}
	conditions.full <- tibble(condition = c(
		"None_0_T1 - None_0_T0",
		"None_0_T2 - None_0_T0",
		"Colistin_0.44_T1 - None_0_T0",
		"Colistin_0.44_T2 - None_0_T0",
		"Rifampicin_0.34_T1 - None_0_T0",
		"Rifampicin_0.34_T2 - None_0_T0",
		"Imipenem_0.06_T1 - None_0_T0",
		"Imipenem_0.06_T2 - None_0_T0",
		"Imipenem_0.09_T1 - None_0_T0",
		"Meropenem_0.11_T1 - None_0_T0",
		"Meropenem_0.11_T2 - None_0_T0",
		"Meropenem_0.17_T1 - None_0_T0",
		"Meropenem_0.17_T2 - None_0_T0"))

conditions.interest <- fread("../../interest.tsv", sep = "\t")

conditions.all <- rbind(conditions.full, conditions.interest) %>% unique

depleted.long <- 
	conditions.all %>% 
	inner_join(
		median_melted_results %>%
			filter(condition %in% c(
				"Colistin_0.44_T2 - None_0_T2",
				"Rifampicin_0.34_T2 - None_0_T2") &
					type == "perfect")) 

mixed <- depleted.long %>%
	mutate(
		depleted = (medLFC < 0 & FDR < 0.01), 
		resistant = (medLFC > 0 & FDR < 0.01)) %>% 
	select(unique_name, condition, depleted, resistant) %>% 
	pivot_longer(!c(condition, unique_name)) %>% 
	mutate(condition = gsub(" - None_0_T2", "", condition)) %>% 
	mutate(condition = gsub("_[0-9\\.]+_", "", condition)) %>% 
	mutate(condition = gsub("T2", "", condition)) %>% 

	mutate(condition = gsub("_[0-9\\.]+_", " ", condition)) %>% 
		unite("condition", c("condition", "name"), sep = " ") %>% 
	pivot_wider(id_cols = unique_name, names_from = condition, values_from = value)

mixed.matrix <- mixed %>%
	make_comb_mat

p <- UpSet(
	mixed.matrix, 
	top_annotation = HeatmapAnnotation(
		"Intersection" = anno_barplot(
			comb_size(mixed.matrix),
			border = FALSE, 
			height = unit(8, "cm"),
			add_numbers = T,
			gp = gpar(fill = c("grey", rep("dark red", 2), rep("grey", 6)), lty = "blank")), 
		show_annotation_name = FALSE),
	right_annotation = rowAnnotation(
		"Genes Significant Beyond Induction at T2" = anno_barplot(
			set_size(mixed.matrix),
			border = FALSE,
			gp = gpar(
				# fill = viridis(set_size(mixed.matrix)/2 %>% length, direction = -1, alpha = 0.5),
				# fill = c(rep("light blue", 2), rep("coral", 2)),
				fill = viridis(2, direction = -1, alpha = 0.35) %>% rep(each = 2), 
				col = c("red", "black", "red", "black"),
				lwd = 3,
				lty = c("dotted", "solid", "dotted", "solid")),
			width = unit(6, "cm"),
			add_numbers = T),
		annotation_name_gp = gpar(fontsize = 8)),
	set_order = set_name(mixed.matrix),
	row_names_gp = grid::gpar(fontsize = 10),
	comb_col = c("black", rep("dark red", 2), rep("black", 6)))

print(p)

```